#! /bin/sh
#
# Honors DEV env variable as the device in case a device
# is not provided as a first (and only) argument. Uses
# lo as default if DEV is also unset.

tc_bin=/sbin/tc

dev=${1:-${DEV:-eth0}}

die() {
  rc=$?
  msg=$1
  echo "!! $msg (rc=$rc)"
  exit $?
}

$tc_bin qdisc del dev $dev root || die "Clearing egress queue failed!"

echo "LTC egress structure cleared:"

echo "--- tc qdiscs for $dev ---"
$tc_bin qdisc show dev $dev || die "Failed to show qdiscs"

echo "--- tc classes for $dev ---"
$tc_bin class show dev $dev || die "Failed to show classes"

echo "--- tc filters for $dev ---"
$tc_bin filter show dev $dev || die "Failed to show filters"

